import { Metadata } from 'next'

export const metadata: Metadata = {
    title: 'Terms of Service — CompetitorGap AI',
    description: 'CompetitorGap AI Terms of Service.',
}

export default function TermsPage() {
    return (
        <div className="min-h-screen bg-ink-950">
            <div className="max-w-3xl mx-auto px-6 py-20">
                <a href="/" className="text-gold text-sm hover:underline mb-8 inline-block">← Back to Home</a>

                <h1 className="font-display text-4xl font-bold text-[var(--text-primary)] mb-4">Terms of Service</h1>
                <p className="text-[var(--text-muted)] mb-12">Last updated: February 2026</p>

                <div className="space-y-8">
                    {[
                        {
                            title: '1. Acceptance of Terms',
                            content: `By creating an account or using CompetitorGap AI ("the Service"), you agree to these Terms of Service. If you do not agree, do not use the Service.`,
                        },
                        {
                            title: '2. Description of Service',
                            content: `CompetitorGap AI provides AI-powered competitive intelligence reports. The Service uses multi-agent AI systems to research and analyze competitive landscapes based on information you provide. Results are informational in nature and not financial, legal, or business advice.`,
                        },
                        {
                            title: '3. Free Tier',
                            content: `The free tier provides one (1) complete competitive intelligence analysis per registered account. This is a one-time allocation — once used, you will need to upgrade to a paid plan for additional analyses. We reserve the right to modify free tier limits with notice.`,
                        },
                        {
                            title: '4. Acceptable Use',
                            content: `You agree NOT to:
• Use the Service to analyze competitors for illegal purposes
• Attempt to circumvent usage limits by creating multiple accounts
• Reverse-engineer, scrape, or extract data from the Service
• Use the Service to generate false or misleading business intelligence
• Share your account credentials with others
• Use automated means to access the Service without prior written consent`,
                        },
                        {
                            title: '5. Accuracy of AI-Generated Content',
                            content: `The competitive intelligence reports are generated by AI systems and are provided "as is." While we strive for accuracy, AI-generated content may contain errors, outdated information, or omissions. You should verify critical business decisions with additional research. We are not liable for decisions made based on AI-generated reports.`,
                        },
                        {
                            title: '6. Intellectual Property',
                            content: `The intelligence reports generated for you based on your company information are your property. The underlying platform, AI systems, algorithms, and technology are owned by CompetitorGap AI. You may not reproduce the platform or its technology without written permission.`,
                        },
                        {
                            title: '7. Privacy',
                            content: `Your use of the Service is subject to our Privacy Policy, which is incorporated into these Terms by reference. By using the Service, you consent to data practices described in our Privacy Policy.`,
                        },
                        {
                            title: '8. Limitation of Liability',
                            content: `To the maximum extent permitted by law, CompetitorGap AI shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including but not limited to loss of revenue, data, goodwill, or business opportunities, resulting from your use of the Service.

Our total liability for any claim arising from these Terms or your use of the Service shall not exceed the amount you paid us in the 12 months preceding the claim.`,
                        },
                        {
                            title: '9. Termination',
                            content: `We may suspend or terminate your account immediately if you violate these Terms. You may terminate your account at any time by contacting us. Upon termination, your right to use the Service ceases.`,
                        },
                        {
                            title: '10. Changes to Terms',
                            content: `We reserve the right to modify these Terms at any time. We will notify you of significant changes via email or a notice on the Service. Continued use of the Service after changes constitutes acceptance of the new Terms.`,
                        },
                        {
                            title: '11. Governing Law',
                            content: `These Terms are governed by the laws of India. Any disputes shall be resolved in the courts of India.`,
                        },
                        {
                            title: '12. Contact',
                            content: `For questions about these Terms:
Email: mustakimnagori076@gmail.com
LinkedIn: linkedin.com/in/mustakimnagori`,
                        },
                    ].map(section => (
                        <section key={section.title}>
                            <h2 className="text-xl font-semibold text-[var(--text-primary)] mb-3">{section.title}</h2>
                            <div className="text-[var(--text-secondary)] leading-relaxed whitespace-pre-line text-sm">
                                {section.content}
                            </div>
                        </section>
                    ))}
                </div>
            </div>
        </div>
    )
}
